#1459 implements a first version (reading) of lazy loading
opral/monorepo pull request #1504
Opened 2023-10-20 14:53 UTC by martin-lysk

2023-10-20 14:54 UTC, martin-lysk commented
I have read the CLA Document and I hereby sign the CLA

2023-11-02 17:22 UTC, felixhaeberle commented
@martin-lysk can't wait for this improvement! 🤩

2023-11-07 12:58 UTC, janfjohannes commented on lix/source-code/client/src/helpers/withLazyFetching.ts
> +	ref: string,
ref, dir, gitdir, oidToFilePaths not required for first version, lets simplify args

2023-11-07 12:58 UTC, janfjohannes commented on lix/source-code/client/src/helpers/withLazyFetching.ts
> +	return new Proxy(fs, {
split the proxy wrapper and the lazzyloading interceptor back

2023-11-07 12:58 UTC, janfjohannes commented on lix/source-code/client/src/isomorphic-git-forks/basename.ts
> +export function basename(path: string) {
// forked files:
// link to whre from incl version, why forked, what was patched

2023-11-07 14:03 UTC, janfjohannes commented on lix/source-code/client/package.json
> +		"path-browserify": "0.0.1",
still used?

2023-11-07 15:46 UTC, janfjohannes commented on lix/source-code/client/src/openRepository.ts
> +	const filePathToOid = {} as { [filePath: string]: string }
replace cached mapping and use either walk ad hoc, or something like raw.listFiles or similar

2023-11-10 16:23 UTC, janfjohannes requested changes

2023-11-10 16:23 UTC, janfjohannes commented on lix/source-code/client/src/isomorphic-git-forks/git-fetch-request-helpers.ts
> +        return Buffer.from(padHex(4, 0), 'utf8');
btw. not sure why you use Buffer here, iso git removed using buffers in its api, could you explain? the iso git http client also does not use the old node buffer plyfill.

2023-11-14 15:49 UTC, janfjohannes requested changes

2023-11-14 15:49 UTC, janfjohannes commented on lix/source-code/client/src/openRepository.ts
> +					filterRefList: { ref: args.branch },
cant we replace filterRefList: { ref: args.branch }, just with ref as argument?

2023-12-11 14:46 UTC, janfjohannes commented on lix/source-code/client/src/helpers/withLazyFetching.ts
> +			const fileOid = filePathToOid[gitFilePath]
todo: only reqyired to ad hoc copy the walk function here.

2023-12-21 15:54 UTC, samuelstroschein commented
@martin-lysk can this PR be closed as stale?

2024-01-02 15:05 UTC, samuelstroschein commented
@janfjohannes can this be closed? @martin-lysk mentioned that you use this PR as a reference

2024-01-03 10:54 UTC, janfjohannes commented
@samuelstroschein  yes, please leave this pr, we use this as base ref of martins proof of concept. i will close this when the lazy loading real implementation is done.

2024-04-30 13:31 UTC, closed without merging

2024-04-30 13:31 UTC, janfjohannes commented
🎉