replaces privateEnv with small util getEnvVar in lix/server
opral/monorepo pull request #2570
Opened 2024-04-11 14:54 UTC by martin-lysk

This one is blocked by #2562 
* [x] merge main in again and remove the `@inlang/env-variables` dependency as soon as #2562  is merged

2024-04-16 22:40 UTC, janfjohannes commented
@martin-lysk  what is the status?

2024-04-18 13:03 UTC, martin-lysk commented
@janfjohannes i removed the depedency from env-variables package - now its ready to review

2024-04-19 01:52 UTC, janfjohannes commented on lix/packages/server/src/util/getEnv.ts
> +	if (!envVar) {
empty string needs to be a valid env variable.

2024-04-19 01:53 UTC, janfjohannes commented on lix/packages/server/src/util/getEnv.ts
> +export function getEnvVar(varName: string, descirption: string, defaultValue?: string) {
description should be optional

2024-04-19 01:54 UTC, janfjohannes commented on lix/packages/server/src/util/getEnv.ts
> +export function getEnvVar(varName: string, descirption: string, defaultValue?: string) {
better have call signature getEnvVar(varname, {default, description})   its more expandable and clear what the args are.

2024-04-19 01:58 UTC, janfjohannes requested changes
see comments

2024-04-19 14:48 UTC, janfjohannes commented
@martin-lysk  as i need this PR i will take over.

2024-04-19 17:22 UTC, janfjohannes approved these changes

2024-04-19 17:27 UTC, merged