Sdk persistence of messages under project directory (MESDK-64)
opral/monorepo pull request #2623
Opened 2024-04-19 18:39 UTC by jldec

Resolves https://github.com/opral/inlang-message-sdk/issues/28

- [x] Feature flagged under project settings `experimental: { persistence: true }`
- [x] override load/store plugin from project settings with sdk built-in persistence
- [x] uses a modified copy of the inlang message format plugin code (for now) 
- [x] also works if no load/store plugin is provided
- [x] cleanup load/store resolvedPluginApi parameter passing in loadProject()
- [x] remove unnecessary wrappers for loadMessages and saveMessages in resolvePlugins.ts 
- [ ] TODO - store full message structure in non-human-editable form (JSON ok)

2024-04-23 17:53 UTC, samuelstroschein requested changes
LGTM but remove the plugin logic. Only two functions `loadMessages()` and `saveMessages()` are required for the feature flag approach

2024-04-23 17:53 UTC, samuelstroschein commented on inlang/source-code/sdk/src/resolve-modules/plugins/resolvePlugins.ts
>  		result.errors.push(new PluginsDoNotProvideLoadOrSaveMessagesError())
can be turned into an if else statement

if (experimentalPersistence){

} else if()

2024-04-23 17:53 UTC, samuelstroschein commented on inlang/source-code/sdk/src/persistence/plugin.ts
> +}
The entire plugin logic is not required. 

The "persistence" can be hacked into: 

```ts
saveMessages(messages){
  JSON.stringify(messsages)
}
loadMessages(fs){
  JSON.parse(fs)
}

```

2024-04-23 17:53 UTC, samuelstroschein commented on inlang/source-code/sdk/src/persistence/plugin.ts
> +	settingsSchema: PluginSettings,
Remove the settings schema to avoid runtime validation errors

2024-04-24 20:18 UTC, jldec commented
@samuelstroschein this should be ready to merge - if you want to take a final look.
@martin-lysk feel free to  👀 and offer feedback also. 
I will not merge before tomorrow morning.

2024-04-24 20:47 UTC, samuelstroschein approved these changes
Let's gooo. 

This is the easiest way to get persistence going. Have a feature flag and a persistency prototype by calling providing "AST dump," `loadMessages` and `saveMessages` functions. 

PS @martin-lysk this solution was the plan of @jldec all the time. The A bunch of miscommunication.

2024-04-24 20:55 UTC, merged