Expose a stopWatching method for createNodeishFsWithWatcher
opral/monorepo pull request #2763
Opened 2024-05-13 14:30 UTC by martin-lysk

This PR exposes a "stopWatching" method for createNodeishFsWithWatcher to avoid passing in a AbortController. This way the function can keep track of its abortController and doesn't hit MaxListenersExceededWarning
`
(node:15668) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit`

2024-05-13 18:10 UTC, jldec requested changes

2024-05-13 18:10 UTC, jldec commented on pnpm-lock.yaml
@martin-lysk why include an updated lockfile in this PR?

2024-05-13 19:22 UTC, martin-lysk commented on pnpm-lock.yaml
thanks for the headsup - local pnpm version messed it up - fixed with last push

2024-05-14 11:34 UTC, jldec approved these changes
LGTM

2024-05-14 11:56 UTC, merged

2024-05-18 16:07 UTC, jldec commented
Resolved https://github.com/opral/inlang-message-sdk/issues/57